apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ros-cluster
  region: ap-south-1

nodeGroups:
   - name: ng1
     desiredCapacity: 1
     instanceType: t2.micro
     ssh:
        publicKeyName: ros
   - name: ng2
     desiredCapacity: 1
     instanceType: t2.small
     ssh:
        publicKeyName: ros
   